repos:
  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint --fix --strict
        language: system
        types: [swift]
      - id: swift-format
        name: swift-format
        entry: swift-format format --in-place --recursive --parallel
        language: system
        types: [swift]
        require_serial: true
      - id: swift-format-lint
        name: swift-format-lint
        entry: swift-format lint --strict --recursive --parallel
        language: system
        types: [swift]
        require_serial: true
