import Foundation

public enum SessionExporter {
    public static let allowedURLSchemes: Set<String> = [
        "http", "https", "mailto", "tel", "ftp",
    ]

    public static func jsonLines<T: Encodable>(_ values: [T]) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.withoutEscapingSlashes]
        var output = Data()
        for value in values {
            output.append(try encoder.encode(value))
            output.append(0x0A)
        }
        return output
    }

    public static func standaloneHTML(
        title: String,
        sessionJSONL: Data,
        renderedTranscript: String,
        leafID: String? = nil
    ) -> String {
        let safeTitle = escapeHTML(title)
        let safeTranscript = sanitizeRenderedHTML(renderedTranscript)
        let encoded = sessionJSONL.base64EncodedString()
        let leaf = escapeJavaScriptString(leafID ?? "")
        return """
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width,initial-scale=1">
              <title>\(safeTitle)</title>
              <style>
                :root{color-scheme:light dark;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
                body{margin:0 auto;max-width:1100px;padding:2rem;line-height:1.5}
                pre{white-space:pre-wrap;overflow-wrap:anywhere}.message{border-left:3px solid #888;padding:.5rem 1rem;margin:1rem 0}
                button{padding:.5rem 1rem}.metadata{opacity:.7}
              </style>
            </head>
            <body>
              <header><h1>\(safeTitle)</h1><button id="download">Download JSONL</button></header>
              <main id="transcript">\(safeTranscript)</main>
              <script>
                "use strict";
                const sessionBase64="\(encoded)";
                const initialLeaf="\(leaf)";
                const bytes=Uint8Array.from(atob(sessionBase64),c=>c.charCodeAt(0));
                document.getElementById("download").addEventListener("click",()=>{
                  const blob=new Blob([bytes],{type:"application/x-ndjson"});
                  const link=document.createElement("a");
                  link.href=URL.createObjectURL(blob);link.download="session.jsonl";link.click();
                  setTimeout(()=>URL.revokeObjectURL(link.href),0);
                });
                if(initialLeaf)document.documentElement.dataset.leafId=initialLeaf;
              </script>
            </body>
            </html>
            """
    }

    public static func safeURL(_ raw: String) -> URL? {
        guard let url = URL(string: raw),
            let scheme = url.scheme?.lowercased(),
            allowedURLSchemes.contains(scheme)
        else {
            return nil
        }
        return url
    }

    public static func escapeHTML(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }

    private static func sanitizeRenderedHTML(_ value: String) -> String {
        // Export callers may provide only pre-rendered plain text and the small
        // message markup generated by Zeta. Script-capable tags are escaped.
        value.replacingOccurrences(
            of: #"(?i)<\s*/?\s*(script|iframe|object|embed|style|link|meta)(?:\s[^>]*)?>"#,
            with: "&lt;$0&gt;",
            options: .regularExpression
        )
        .replacingOccurrences(
            of: #"(?i)\s+on[a-z]+\s*=\s*([\"']).*?\1"#,
            with: "",
            options: .regularExpression
        )
        .replacingOccurrences(
            of: #"(?i)(href|src)\s*=\s*([\"'])\s*javascript:[^\"']*\2"#,
            with: "$1=\"#\"",
            options: .regularExpression
        )
    }

    private static func escapeJavaScriptString(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\u{2028}", with: "\\u2028")
            .replacingOccurrences(of: "\u{2029}", with: "\\u2029")
            .replacingOccurrences(of: "<", with: "\\u003c")
    }
}
